name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm i
        working-directory: client

      - name: Deploy
        run: npm run deploy
        working-directory: client
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}